joint_limits:
  virtual_joint/x:
    min_position: -10.0
    max_position: 10.0
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 0.5
  virtual_joint/y:
    min_position: -10.0
    max_position: 10.0
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 0.5
  virtual_joint/theta:
    min_position: -3.1415926535898
    max_position: 3.1415926535898 
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 0.5
